language: node_js

node_js:
  - node

cache: yarn

before_install: yarn global add greenkeeper-lockfile@1

script:
  - yarn build
  - yarn lint
  - yarn test

after_script: greenkeeper-lockfile-upload
