language: node_js

node_js:
  - node

cache: yarn

before_install: yarn global add greenkeeper-lockfile@1

install: yarn install --ignore-scripts

script:
  - yarn run lint
  - yarn run flow
  - yarn run test
  - yarn run build

after_script: greenkeeper-lockfile-upload
